### PR TITLE
Updated project to .NET Framework 4.8.

### PR DESCRIPTION
**Pull request by codedChaos**
ChangleLog:
    * modify: bump version to 1.2.0 in src/KeePassDPG/Properties/AssemblyInfo.cs
    * create PLGX from updated local source files
    * test new PLGX version
    * create sha256 hashes of PLGX files for original author's review
    * store review files in <project-root>/PLGX/ directory
    * take screenshots of errant behavior and fixed behavior
    * store screenshots in PLGX/ directory beside their respective files

Signed-off-by: William Smyth <codedchaos@zohomail.com>

Commit History:

 > This is the commit message #2:
```
    Create test/proof files
   
    - Add PLGX file newly generated with fix
    - Add original PLGX file from author's releases
    - create checksums of PLGX using sha256
    - test sha256 hashes for PLGX files against shasum.bat to ensure
      they match the same hashes produced in BASH
   
    Signed-off-by: William Smyth <codedchaos@zohomail.com>
```

 > This is the commit message #3:
```
    Add screenshots of KeePass UI -> Plugins
   
    - show original PLGX from release by original author
    - show updated PLGX after modification of AssemblyInfo.cs
   
    Signed-off-by: William Smyth <codedchaos@zohomail.com>
```

### CODE REVIEW

**Comment by quinterojose** [comment]
Good catch. I don't usually keep the PLGX in the repo so I will remove before merging. I let the release pipeline build and release the PLGX when I push a new tag. Also, I have already released 1.2 so this will technically be 1.2.1. Would you mind updating AssemblyInfo.cs and plugin-version.txt to reflect the new version?

**Comment by codedChaos** [comment]
> Good catch. I don't usually keep the PLGX in the repo so I will remove before merging. I let the release pipeline build and release the PLGX when I push a new tag. Also, I have already released 1.2 so this will technically be 1.2.1. Would you mind updating AssemblyInfo.cs and plugin-version.txt to reflect the new version?

I don't mind at all. I'll knock that out today. 

As for PLGX, I figured as much but since this was kind of a first pull request on my part, I wanted to make sure that I could prove that what I had done actually worked. I assumed you'd get rid of the entire PLGX folder that I created in the root of the project.

I even spent longer than I'll admit on cleaning up my git history, commits, and reflog. :)

**Comment by codedChaos** [comment]
I'm updating the requested files now and will have an update PR to you shortly. Sorry for the delay, had a FileSystem debacle on my dev laptop to recover from and a couple sick kids at home all week to contend with.

**Comment by codedChaos** [comment]
Closing this PR since opening v1.2.1 PR

**Pull request closed without merging**
